### ISSUE TITLE
 Error: Exception: Error from AI package: RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by DiRuffy** [dj-yacine-flutter/brain_fusion#1]
I am getting this two exception in your provided example.  

Error: Exception: Error from AI package: RangeError (index): Invalid value: Valid value range is empty: 0

Exception: Error from AI package: HTTP request failed. Client is already closed.

How can we fix this and what does this mean?

**Comment by dj-yacine-flutter** [comment]
hey . thanks for use the package 

the error you see was fix in the latest release 0.0.6

also in mobile devices  don't forget to add internet permission in your app

**Comment by Ravan1190** [comment]
how can i make the generated image downloadable ?

**Comment by dj-yacine-flutter** [comment]
> how can i make the generated image downloadable ?

use dart:io and create file with png extention

**Comment by Ravan1190** [comment]
Sir, can you add it in example please. 

Thank You.
