### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BerylHitech** [dj-yacine-flutter/brain_fusion#11]
I am getting Error: Exception: Error from AI package: Failed host lookup: 'api.brainfusion.ai'. I tried using my app on different phones different networks but still I am facing this error

**Comment by KarlMathuthu** [comment]
Update your package to this latest version.

brain_fusion: ^0.0.9

**Comment by BerylHitech** [comment]
still facing same error

**Comment by dj-yacine-flutter** [comment]
> still facing same error

can you give us more details or the code

**Comment by KarlMathuthu** [comment]
Post your code here and let's check please.

**Comment by albste** [comment]
> I am getting Error: Exception: Error from AI package: Failed host lookup: 'api.brainfusion.ai'. I tried using my app on different phones different networks but still I am facing this error

If you are running the app on Android devices, you must add internet permission on AndroidManifest.xml.

**Comment by KarlMathuthu** [comment]
Did it work for you?

**Comment by albste** [comment]
Yes, but now there is another error with the API: Error from AI package: Exception: check queue code :404. It seems that the service is no longer working

**Comment by KarlMathuthu** [comment]
Ok, For me too it was working before, but now, facing the same error

**Comment by dj-yacine-flutter** [comment]
update to the latest version 0.1
