### ISSUE TITLE
when I execute on flutter web error 400 is occured

### ISSUE THREAD

**Issue by jkandrea** [dj-yacine-flutter/brain_fusion#13]
Error: Exception: Error from AI package: Exception : run code :400

**Comment by dj-yacine-flutter** [comment]
> Error: Exception: Error from AI package: Exception : run code :400

Just Flutter web or all platforms ??

**Comment by jkandrea** [comment]
I'm sorry it is okay now.
Error was just in my office PC.
thank you for your comment

**Comment by dj-yacine-flutter** [comment]
update to the latest version 0.1
