### ISSUE TITLE
The package stopped working

### ISSUE THREAD

**Issue by Joe2316** [dj-yacine-flutter/brain_fusion#14]
I tried the package but it doesn't work can you check it, please?

**Comment by dj-yacine-flutter** [comment]
> I tried the package but it doesn't work can you check it, please?

What error you get

**Comment by Joe2316** [comment]
Error: Exception: Error from AI package check queue code:404

**Comment by albste** [comment]
> Error: Exception: Error from AI package check queue code:404

I have the same error, how to fix it?

**Comment by Joe2316** [comment]
@dj-yacine-flutter can you fix it please

**Comment by dj-yacine-flutter** [comment]
> @dj-yacine-flutter can you fix it please  
> 
> Error: Exception: Error from AI package check queue code:404
> 
> 

I'm working on it ☺️

**Comment by dj-yacine-flutter** [comment]
Tomorrow will be fixed I will add new styles and image resolutions 🤠

**Comment by KarlMathuthu** [comment]
I'm counting on you bro ❤️😍

**Comment by matifdeveloper** [comment]
> I'm counting on you bro ❤️😍

Same here bro

**Comment by dj-yacine-flutter** [comment]
update to the latest version 0.1
