### ISSUE TITLE
Exception: Error from AI package: Exception: check queue code :404

### ISSUE THREAD

**Issue by KarlMathuthu** [dj-yacine-flutter/brain_fusion#16]

**Comment by ajlank** [comment]
Hello,
Another issue is here with your code=>Exception: Error from AI package: Exception: check queue code :404

**Comment by dj-yacine-flutter** [comment]
update to the latest version 0.1

**Comment by KarlMathuthu** [comment]
Thank you bro ❤️🔥🔥
