### ISSUE TITLE
Fusion brain API url

### ISSUE THREAD

**Issue by albste** [dj-yacine-flutter/brain_fusion#17]
Is there any documentation with urls for the fusion brain API? Where can I find the endpoints? I searched on google but couldn't find anything

**Comment by dj-yacine-flutter** [comment]
> Is there any documentation with urls for the fusion brain API? Where can I find the endpoints? I searched on google but couldn't find anything

Because it's based on web scraping just wait 2 hours and I will publish the new version

**Comment by dj-yacine-flutter** [comment]
update to the latest version 0.1
