### ISSUE TITLE
Why remove some styles?

### ISSUE THREAD

**Issue by matifdeveloper** [dj-yacine-flutter/brain_fusion#18]
Is these are replaced are removed?
1. AIStyle.islamic
2. AIStyle.mosaic
3. AIStyle.iconography

**Comment by dj-yacine-flutter** [comment]
> Is these are replaced are removed?
> 1. AIStyle.islamic
> 2. AIStyle.mosaic
> 3. AIStyle.iconography

Sorry 😔 but the API was changed and the styles now are stored locally in the server not in the package like previous version and I didn't find these styles on the server right now

**Comment by matifdeveloper** [comment]
Okay bro thanks 💖
