### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by achyuth4** [dj-yacine-flutter/brain_fusion#20]
Please I'm new to Bart and Yaml languages. can anyone please help me to run this and how to run in browser also. please?

**Comment by Aksoylu** [comment]
Try to 
Developers of this tech are amateur as hell. They didn't share even API doc about their work. If you wan't to try brain fusion in web, you should export http request headers, body and params from flutter code below:
[code](https://github.com/dj-yacine-flutter/brain_fusion/blob/master/lib/src/api/run.dart)
