### ISSUE TITLE
Is there any API limitations or something like that?

### ISSUE THREAD

**Issue by Aksoylu** [dj-yacine-flutter/brain_fusion#21]
I investigated website of [FusionBrain.ai](https://fusionbrain.ai/diffusion) for my question but i couldn't get any answers.
When i was firstly started the using package; API was returning me images with given prompt but suddenly API started to return null without throwing any errors.

`    Uint8List? image = await AiService.ImageAi?.runAI(content, AIStyle.oilPainting, Resolution.r1x1);
`

I mean, this functions returns null for me. And it was working one day ago. I couldn't understand why this is happening.
Is there any IP addr or device ID based limitation exist ? Or this is just a server down error ?

**Comment by achyuth4** [comment]
No API limitations. because we are running locally using models, so no API Limitations.

**Comment by dj-yacine-flutter** [comment]
> No API limitations. because we are running locally using models, so no API Limitations.

This is wrong. The API have limitations when choosing styles. But not when generate images

**Comment by Zabadam** [comment]
> This is wrong. The API have limitations when choosing styles. But not when generate images

Can you elaborate on this? Calling `AI().runAI()` requires an `AIStyle`. 
Do you mean that `AIStyle.noStyle` will have no limit, but any other style does?
