### ISSUE TITLE
Getting 404 errors 

### ISSUE THREAD

**Issue by fdchiu** [dj-yacine-flutter/brain_fusion#23]
Starting recently (as recent as July 26), the app always display errors: check queue code 404

No image was generated no matter what style is selected. The web site of fusion brain seems working fine. Is the API server down or end point changed?

**Comment by KarlMathuthu** [comment]
Update the package to the latest version

brain_fusion: ^0.1.1

**Comment by fdchiu** [comment]
tested 0.1.1, it's working. thanks!
