### ISSUE TITLE
please explain me how to run step to step brother please? please bro!

### ISSUE THREAD

**Issue by achyuth4** [dj-yacine-flutter/brain_fusion#24]
bro can you please lend your time and please teach me step by step to run the Brain Fusion bro. please bro, like install the ide, run this or that command. like that teach me bro, please bro.

**Comment by achyuth4** [comment]
Please explain bro

**Comment by dj-yacine-flutter** [comment]
> Please explain bro

Look bro this package is just API to the AI not the model

**Comment by achyuth4** [comment]
ok ok!
