### ISSUE TITLE
Filters generate similar images 

### ISSUE THREAD

**Issue by serhaterfidan** [dj-yacine-flutter/brain_fusion#26]
Hello for example when I selected anime or realistic or pencil drawn always generated realistic photos I think filters not work can you help me

**Comment by serhaterfidan** [comment]
I meaned styles not working

**Comment by dj-yacine-flutter** [comment]
> I meaned styles not working

If any style doesn't work that means it's from the AI servers. I will check this soon 🔜🙂

**Comment by serhaterfidan** [comment]
if styles can work it will be very nice and I wanna know api limitations also

**Comment by serhaterfidan** [comment]
styles now working thanks :)

**Comment by KarlMathuthu** [comment]
Please close this issue
