### ISSUE TITLE
The package stopped working 

### ISSUE THREAD

**Issue by Joe2316** [dj-yacine-flutter/brain_fusion#27]
I tried the package but it doesn't work, keep buffering can you check it, please?

**Comment by RomanBhimani** [comment]
same issue what's the solution

**Comment by KarlMathuthu** [comment]
The issue is not from this package actually, but it's from the developers of fusion brain itself.

**Comment by mohsinnaqvi505** [comment]
Same issue. But it from the developer of fusion brain.

Nothing wrong with package
https://fusionbrain.ai/en/

**Comment by KarlMathuthu** [comment]
Since i have my app on the Google Play Store live, I can't really wait for brain fusion to fix this error while users put 1 stars, So as we are talking now i'm shipping the api to the paid api for this time only while those developers fix the issue.

**Comment by RomanBhimani** [comment]
there are any proper solution?

**Comment by KarlMathuthu** [comment]
As for now i really don't think there is another thing we can do other than to wait for them to fix the brain fusion's original server.

**Comment by RomanBhimani** [comment]
> 

same here brother there are many active user in the app and it's not working it is a very loss for us

**Comment by KarlMathuthu** [comment]
So what are you going to do now?

Do you have any idea?

**Comment by KarlMathuthu** [comment]
I'm about to publish a new version now on Google Play Store

**Comment by RomanBhimani** [comment]
we can start a new package 

https://pub.dev/packages/openai_dalle_wrapper

**Comment by RomanBhimani** [comment]
but in this package a some limimtations

**Comment by KarlMathuthu** [comment]
You have a plan. Do you know who owns that package?

**Comment by RomanBhimani** [comment]
no i don't have any idea but i research this package but there are some limitions

**Comment by RomanBhimani** [comment]
> I'm about to publish a new version now on Google Play Store

what's the update package is not working

**Comment by KarlMathuthu** [comment]
> > I'm about to publish a new version now on Google Play Store
> 
> what's the update package is not working

I knew this was gonna happen so i created a new in app package, So i just commented using this one and uncommented that backup package.

**Comment by KarlMathuthu** [comment]
> no i don't have any idea but i research this package but there are some limitions

Yes it really does, I once checked on it before. It needs premium only, No free api keys and they are very expensive.

**Comment by RomanBhimani** [comment]
can you share me which is the other package then my work is done

**Comment by KarlMathuthu** [comment]
I created it myself but it's not yet perfect. I want to perfect it just now when i'm done uploading the new version.

**Comment by KarlMathuthu** [comment]
I used this api, check it also brother, It may help you.

[https://api.stability.ai/docs#tag/v1generation/operation/textToImage](url)

**Comment by RomanBhimani** [comment]
what's the name of your app?

**Comment by KarlMathuthu** [comment]
I haven't published the new version yet.

**Comment by KarlMathuthu** [comment]
[https://play.google.com/store/apps/details?id=com.karlmathuthu.dream_ai_art_generator](url)

Here it is, May i see yours please.

**Comment by RomanBhimani** [comment]
My app is not live on play store now I was supposed to live today

**Comment by KarlMathuthu** [comment]
Oh i see, I'm sorry you have to face problems before it's live.

**Comment by RomanBhimani** [comment]
which frame work use to make this app

**Comment by KarlMathuthu** [comment]
Flutter

**Comment by RomanBhimani** [comment]
> Oh i see, I'm sorry you have to face problems before it's live.

yes bad luck!

**Comment by RomanBhimani** [comment]
> Flutter

okkay

**Comment by RomanBhimani** [comment]
can you help me to set a new api i don't have any idea of it

**Comment by KarlMathuthu** [comment]
Ok sure, Rate your flutter skills out of 10. I want to know your experience.

**Comment by RomanBhimani** [comment]
7.5

**Comment by KarlMathuthu** [comment]
Oh okay no problem brother. I think it's better we use whatsapp to talk, Not here.

**Comment by RomanBhimani** [comment]
okay

**Comment by RomanBhimani** [comment]
please give me your mobile number in my personal mail

**Comment by KarlMathuthu** [comment]
Send m your email

**Comment by RomanBhimani** [comment]
romanyt2103@gmail.com

**Comment by KarlMathuthu** [comment]
Check your email inbox

**Comment by RomanBhimani** [comment]
okay i send you message please check

**Comment by KarlMathuthu** [comment]
Good news everybody, The server is finally fixed.

![Screenshot 2023-08-16 111158](https://github.com/dj-yacine-flutter/brain_fusion/assets/116157611/21953578-3965-407e-a5fd-1d88caefe1f0)
