### ISSUE TITLE
Failed host lookup

### ISSUE THREAD

**Issue by Mohamed-kamel-1994** [dj-yacine-flutter/brain_fusion#29]
every time i'm trying to run 
Uint8List image = await ai.runAI(query, AIStyle.noStyle, Resolution.r1x1);

i get this error =>   throw createError(response, "Failed host lookup: '$host'");
// host : "api.fusionbrain.ai"

i did every step like the Example

**Comment by KarlMathuthu** [comment]
Please provide me your code you tried with.

**Comment by Mohamed-kamel-1994** [comment]
// note that i'm using getx
// InternetConnectionChecker to check if ther is internet
// the error in this line  Uint8List image = await ai.runAI(query, AIStyle.noStyle, Resolution.r1x1);

// controller class
class MainController extends GetxController{

  final TextEditingController textEditingController = TextEditingController();
  final AI ai = AI();

  RxList<Widget> widgets = <Widget>[].obs;

  bool run = false;

  Future generateImage() async {
    if (run == true) return;
    run = true;

    bool result = await InternetConnectionChecker().hasConnection;
    
    if(result == false) return;

    String query = textEditingController.text;

    textEditingController.clear();

    widgets.add(Text(query));

    Uint8List image = await ai.runAI(query, AIStyle.noStyle, Resolution.r1x1);

    widgets.add(Image.memory(image));
    run = false;

    print("========== done ==============");
  }

  @override
  void dispose() {
    textEditingController.dispose();
    super.dispose();
  }
}

// view
 final controller = Get.put(MainController());
    return Scaffold(
      body: SafeArea(
        child: Container(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          margin: const EdgeInsets.all(ValuesRes.v8),
          child: Column(
            children: [
              Expanded(
                child: GetX<MainController>(
                  builder: (controller) => ListView(
                    children: controller.widgets,
                  ),
                  )),
              TextFormField(
                controller: controller.textEditingController,
                minLines: ValuesRes.minLines,
                maxLines: ValuesRes.maxLines,
                style: Theme.of(context).textTheme.headlineMedium,
                decoration: InputDecoration(
                  hintText: "hint".tr
                ),
              ),
              const SizedBox(height: ValuesRes.v8,),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                child: ElevatedButton(
                  onPressed: (){
                    controller.generateImage();
                  }, child: Text("generate".tr)),
              )
            ],
          ),
        )
      ),
    );

**Comment by Mohamed-kamel-1994** [comment]
> Please provide me your code you tried with.

// note that i'm using getx
// InternetConnectionChecker to check if ther is internet
// the error in this line  Uint8List image = await ai.runAI(query, AIStyle.noStyle, Resolution.r1x1);

// controller class
`class MainController extends GetxController{

  final TextEditingController textEditingController = TextEditingController();
  final AI ai = AI();

  RxList<Widget> widgets = <Widget>[].obs;

  bool run = false;

  Future generateImage() async {
    if (run == true) return;
    run = true;

    bool result = await InternetConnectionChecker().hasConnection;
    
    if(result == false) return;

    String query = textEditingController.text;

    textEditingController.clear();

    widgets.add(Text(query));

    Uint8List image = await ai.runAI(query, AIStyle.noStyle, Resolution.r1x1);

    widgets.add(Image.memory(image));
    run = false;

    print("========== done ==============");
  }

  @override
  void dispose() {
    textEditingController.dispose();
    super.dispose();
  }
}
`
// view
` final controller = Get.put(MainController());
    return Scaffold(
      body: SafeArea(
        child: Container(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          margin: const EdgeInsets.all(ValuesRes.v8),
          child: Column(
            children: [
              Expanded(
                child: GetX<MainController>(
                  builder: (controller) => ListView(
                    children: controller.widgets,
                  ),
                  )),
              TextFormField(
                controller: controller.textEditingController,
                minLines: ValuesRes.minLines,
                maxLines: ValuesRes.maxLines,
                style: Theme.of(context).textTheme.headlineMedium,
                decoration: InputDecoration(
                  hintText: "hint".tr
                ),
              ),
              const SizedBox(height: ValuesRes.v8,),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                child: ElevatedButton(
                  onPressed: (){
                    controller.generateImage();
                  }, child: Text("generate".tr)),
              )
            ],
          ),
        )
      ),
    );
`

**Comment by KarlMathuthu** [comment]
Please update your package to the latest version

brain_fusion: ^0.1.1

After this please let me know if you getting an error. Thanks.

**Comment by Mohamed-kamel-1994** [comment]
> Please update your package to the latest version
> 
> brain_fusion: ^0.1.1
> 
> After this please let me know if you getting an error. Thanks.

I already use it

  get: ^4.6.5
  brain_fusion: ^0.1.1
  lottie: ^2.6.0
  url_launcher: ^6.1.12
  internet_connection_checker: ^1.0.0+1

I tried the app on the emulator and on a real device, but the same problem

Is it possible that the geographical location is the cause of the problem because I work from Kingdom of Saudi Arabia ?

**Comment by KarlMathuthu** [comment]
No, i don't think that's the problem. Let's see if that is the cause. Clone the example project that i put on this package and run it then share the video or the screenshots.

[https://github.com/dj-yacine-flutter/brain_fusion/tree/master/example](url)

**Comment by Mohamed-kamel-1994** [comment]
> No, i don't think that's the problem. Let's see if that is the cause. Clone the example project that i put on this package and run it then share the video or the screenshots.
> 
> [https://github.com/dj-yacine-flutter/brain_fusion/tree/master/example](url)

the same error

![Screenshot 2023-08-18 203218](https://github.com/dj-yacine-flutter/brain_fusion/assets/75671054/2a3d22c1-c3e3-4125-8f03-dfcb9003e56c)
![Screenshot 2023-08-18 203353](https://github.com/dj-yacine-flutter/brain_fusion/assets/75671054/bc26f70e-ae98-4907-82c7-1d6535c3f3d1)
![Untitle8888d](https://github.com/dj-yacine-flutter/brain_fusion/assets/75671054/a4d7b9d9-0272-4890-9419-e82c923e5930)

**Comment by KarlMathuthu** [comment]
add <uses-permission android:name="android.permission.INTERNET" /> in android/app/src/main/AndroidManifest.xml and then turn off your emulator then start it again. Hope this helps.

**Comment by Mohamed-kamel-1994** [comment]
> add in android/app/src/main/AndroidManifest.xml and then turn off your emulator then start it again. Hope this helps.

what shoud i add !!

**Comment by Mohamed-kamel-1994** [comment]
> add in android/app/src/main/AndroidManifest.xml and then turn off your emulator then start it again. Hope this helps.

this is AndroidManifest from my app what do you suggests to do

![Screenshot 2023-08-18 230200](https://github.com/dj-yacine-flutter/brain_fusion/assets/75671054/5f58ece8-32fa-4e04-a90d-f5dd447a3ed8)
