### ISSUE TITLE
Not Working Properly

### ISSUE THREAD

**Issue by BerylHitech** [dj-yacine-flutter/brain_fusion#3]
I was using this i tested it on 3 devices out three it's working for only 1 device

**Comment by dj-yacine-flutter** [comment]
> I was using this i tested it on 3 devices out three it's working for only 1 device

Check internet permission . Tell me where is the problem exactly

**Comment by BerylHitech** [comment]
when i try to generate image it's showing Error: Exception: Error from AI package: Failed host lookup: 'fusionbrain.ai'

**Comment by dj-yacine-flutter** [comment]
The problem was fixed successfully
