### ISSUE TITLE
Error : Exception : Error from AI package : Exception : run code : 401

### ISSUE THREAD

**Issue by KarlMathuthu** [dj-yacine-flutter/brain_fusion#32]
Hi owner, Please help us fix this error ASAP. I recently saw that fusionbrain.io have implemented the login and signup to use their website. So is there a way to fix this?, If there is, Please contact me so i can help you do it ASAP. Here's my email karlmathuthu11@gmail.com. Thanks brother.

**Comment by triay0** [comment]
+1 please help

**Comment by mohsinnaqvi0606** [comment]
I think owner have changed something! Website is working now [Fusion Brain](https://editor.fusionbrain.ai/)
but plugin is still giving error

**Comment by triay0** [comment]
yes but now asks for an auth

**Comment by KarlMathuthu** [comment]
The error we are getting is 401 which means **the client request has not been completed because it lacks valid authentication credentials for the requested resource.**. So that's what we all should figure out.

**Comment by KarlMathuthu** [comment]
So my question is, If it lacks the valid authentication, How about if we authenticate using our accounts credentials that we created from their website. Do ya'll think it's possible?, Please let me know if you have an idea then we'll solve this problem. Thank you.

**Comment by PrijensNakrani** [comment]
now it is working and fusion brain website removed sign up flow

**Comment by KarlMathuthu** [comment]
Really?

**Comment by PrijensNakrani** [comment]
now it is not working and fusion brain website placed sign up flow again
