### ISSUE TITLE
Package fails so much

### ISSUE THREAD

**Issue by triay0** [dj-yacine-flutter/brain_fusion#37]
I get this error a lot of times:

 Exception: Error from AI package: Exception: Failed to generate the image in the server"

**Comment by dj-yacine-flutter** [comment]
> I get this error a lot of times:
> 
>  Exception: Error from AI package: Exception: Failed to generate the image in the server"

I will check it

**Comment by dj-yacine-flutter** [comment]
sorry. but the website now have a sessions token technique that expire every minute so we can`t bypass it . now the package will be archive .
