### ISSUE TITLE
Package stopped working and fusionbrain now has signup

### ISSUE THREAD

**Issue by Joe2316** [dj-yacine-flutter/brain_fusion#39]
The package stopped working only buffering after fusionbrain had signup check it please

**Comment by triay0** [comment]
yes return error 401, please help

**Comment by dj-yacine-flutter** [comment]
> yes return error 401, please help

Ok I will try my best

**Comment by averdeminal** [comment]
> > yes return error 401, please help
> 
> Ok I will try my best

Hello, any news?
