### ISSUE TITLE
Just stopped working

### ISSUE THREAD

**Issue by KarlMathuthu** [dj-yacine-flutter/brain_fusion#7]
Hi the API just stopped working please fix that as soon as possible if you can.

If you need some help in contributing to this package please let us know because we really use this package a lot and our projects just stopped working.

**Comment by KarlMathuthu** [comment]
I think i found something guys,I will try to make a flutter package similar to this one,I will let you all know when i'm done.

**Comment by KarlMathuthu** [comment]
Here is what i found guys let me share.

This package used an API from another ai website so i think this awesome guy has been paying this for us but suddenly stopped,That's why we got the error.So i think how about if we create our own function without using the package for the mean time while it's being fixed.Follow how i did it,If you have any questions please comment and i will reply.Thank you.

//First create your account to get the API key https://dreamstudio.ai/account/

//Create a UI8List variable like this.
Uint8List? imageData;

//Then create this function which will help you generate your images from the AI.
 void generateImage() async {

    const baseUrl = 'https://api.stability.ai';
    final url = Uri.parse(
        '$baseUrl/v1alpha/generation/stable-diffusion-512-v2-0/text-to-image');

    // Make the HTTP POST request to the Stability Platform API
    final response = await http.post(
      url,
      headers: {
        'Content-Type': 'application/json',
        'Authorization':
            'Bearer sk-////put your api key',
        'Accept': 'image/png',
      },
      body: jsonEncode({
        'cfg_scale': 7,
        'clip_guidance_preset': 'FAST_BLUE',
        'height': 512,
        'width': 512,
        'samples': 1,
        'steps': 50,
        'text_prompts': [
          {
            'text':
                "textEditingController.text" ??
                    '',
            'weight': 1,
          }
        ],
      }),
    );

    
    if (response.statusCode != 200) {
      print("success");
    } else {
      try {
        imageData = (response.bodyBytes);
        setState(() {});
      } on Exception catch (e) {
        print(e);
      }
    }
  }


Hope it helps.

**Comment by dj-yacine-flutter** [comment]
I will fix it soon

**Comment by KarlMathuthu** [comment]
Thank you 

I will be waiting Sir.

**Comment by dj-yacine-flutter** [comment]
The problem was fixed successfully
